spring:
  aop:
    auto: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.103.70.243:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    jdbc-type-for-null: null
    map-underscore-to-camel-case: false

server:
  port: 8088

logging:
  level:
    cn.wy.bs.mapper: debug